# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ranges.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QComboBox, QCheckBox,
    QDoubleSpinBox, QLabel, QLineEdit, QGroupBox, QFormLayout, QSpinBox, QAbstractSpinBox
)

class Ui_ranges(object):
    def setupUi(self, ranges):
        ranges.setObjectName("ranges")
        ranges.resize(389, 450)
#        ranges.resize(400, 500)
#        ranges.setMinimumSize(QtCore.QSize(300, 550))
        ranges.setMinimumSize(QtCore.QSize(300, 425))
        ranges.setMaximumSize(QtCore.QSize(466, 450))
        self.verticalLayout = QtWidgets.QVBoxLayout(ranges)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtWidgets.QLabel(ranges)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.filePath = QtWidgets.QLineEdit(ranges)
        self.filePath.setMinimumSize(QtCore.QSize(0, 20))
        self.filePath.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.filePath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filePath.setObjectName("filePath")
        self.horizontalLayout.addWidget(self.filePath)
        self.selectFileButton = QtWidgets.QPushButton(ranges)
        self.selectFileButton.setMinimumSize(QtCore.QSize(0, 20))
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout.addWidget(self.selectFileButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(ranges)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.isSpaceMap = QtWidgets.QCheckBox(ranges)
        self.isSpaceMap.setEnabled(True)
        self.isSpaceMap.setMaximumSize(QtCore.QSize(100, 16777215))
        self.isSpaceMap.setChecked(True)
        self.isSpaceMap.setObjectName("isSpaceMap")
        self.horizontalLayout_3.addWidget(self.isSpaceMap)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.squareMeas = QtWidgets.QCheckBox(ranges)
        self.squareMeas.setObjectName("squareMeas")
        self.gridLayout.addWidget(self.squareMeas, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(ranges)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ranges)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(ranges)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(ranges)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(ranges)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.yMeasMax = QtWidgets.QDoubleSpinBox(ranges)
        self.yMeasMax.setMinimumSize(QtCore.QSize(0, 20))
        self.yMeasMax.setMaximum(150.0)
        self.yMeasMax.setProperty("value", 140.0)
        self.yMeasMax.setObjectName("yMeasMax")    
        self.gridLayout.addWidget(self.yMeasMax, 3, 3, 1, 1)
        self.yMeasStep = QtWidgets.QDoubleSpinBox(ranges)
        self.yMeasStep.setMinimumSize(QtCore.QSize(0, 20))
        self.yMeasStep.setMaximum(150.0)
        self.yMeasStep.setSingleStep(0.1)
        self.yMeasStep.setProperty("value", 1.5)
        self.yMeasStep.setObjectName("yMeasStep")
        self.gridLayout.addWidget(self.yMeasStep, 3, 2, 1, 1)
        self.xMeasMin = QtWidgets.QDoubleSpinBox(ranges)
        self.xMeasMin.setMinimumSize(QtCore.QSize(0, 20))
        self.xMeasMin.setMaximum(150.0)
        self.xMeasMin.setProperty("value", 10.0)
        self.xMeasMin.setObjectName("xMeasMin")
        self.gridLayout.addWidget(self.xMeasMin, 1, 1, 1, 1)
        self.yMeasMin = QtWidgets.QDoubleSpinBox(ranges)
        self.yMeasMin.setMinimumSize(QtCore.QSize(0, 20))
        self.yMeasMin.setMaximum(150.0)
        self.yMeasMin.setProperty("value", 10.0)
        self.yMeasMin.setObjectName("yMeasMin")
        self.gridLayout.addWidget(self.yMeasMin, 3, 1, 1, 1)
        self.xMeasStep = QtWidgets.QDoubleSpinBox(ranges)
        self.xMeasStep.setMinimumSize(QtCore.QSize(0, 20))
        self.xMeasStep.setMaximum(150.0)
        self.xMeasStep.setSingleStep(0.1)
        self.xMeasStep.setProperty("value", 1.5)
        self.xMeasStep.setObjectName("xMeasStep")
        self.gridLayout.addWidget(self.xMeasStep, 1, 2, 1, 1)
        self.xMeasMax = QtWidgets.QDoubleSpinBox(ranges)
        self.xMeasMax.setMinimumSize(QtCore.QSize(0, 20))
        self.xMeasMax.setMaximum(150.0)
        self.xMeasMax.setProperty("value", 140.0)
        self.xMeasMax.setObjectName("xMeasMax")
        self.gridLayout.addWidget(self.xMeasMax, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_10 = QtWidgets.QLabel(ranges)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.wavePlotMax = QtWidgets.QDoubleSpinBox(ranges)
        self.wavePlotMax.setMinimumSize(QtCore.QSize(0, 20))
        self.wavePlotMax.setMaximum(999999999.0)
        self.wavePlotMax.setProperty("value", 1000.0)
        self.wavePlotMax.setObjectName("wavePlotMax")
        self.gridLayout_3.addWidget(self.wavePlotMax, 4, 2, 1, 1)
        self.yPlotMin = QtWidgets.QDoubleSpinBox(ranges)
        self.yPlotMin.setMinimumSize(QtCore.QSize(0, 20))
        self.yPlotMin.setMinimum(-999999999.0)
        self.yPlotMin.setMaximum(999999999.0)
        self.yPlotMin.setProperty("value", 10.0)
        self.yPlotMin.setObjectName("yPlotMin")
        self.gridLayout_3.addWidget(self.yPlotMin, 3, 1, 1, 1)
        self.yPlotFullscale = QtWidgets.QPushButton(ranges)
        self.yPlotFullscale.setMinimumSize(QtCore.QSize(0, 20))
        self.yPlotFullscale.setObjectName("yPlotFullscale")
        self.gridLayout_3.addWidget(self.yPlotFullscale, 3, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(ranges)
        self.label_11.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(ranges)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(ranges)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.colorPlotFullscale = QtWidgets.QPushButton(ranges)
        self.colorPlotFullscale.setObjectName("colorPlotFullscale")
        self.horizontalLayout_5.addWidget(self.colorPlotFullscale)
        self.colorPlotAutoscale = QtWidgets.QPushButton(ranges)
        self.colorPlotAutoscale.setObjectName("colorPlotAutoscale")
        self.horizontalLayout_5.addWidget(self.colorPlotAutoscale)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 6, 3, 1, 1)
        self.xPlotMax = QtWidgets.QDoubleSpinBox(ranges)
        self.xPlotMax.setMinimumSize(QtCore.QSize(0, 20))
        self.xPlotMax.setMinimum(-999999999.0)
        self.xPlotMax.setMaximum(999999999.0)
        self.xPlotMax.setProperty("value", 140.0)
        self.xPlotMax.setObjectName("xPlotMax")
        self.gridLayout_3.addWidget(self.xPlotMax, 2, 2, 1, 1)
        self.yPlotMax = QtWidgets.QDoubleSpinBox(ranges)
        self.yPlotMax.setMinimumSize(QtCore.QSize(0, 20))
        self.yPlotMax.setMinimum(-999999999.0)
        self.yPlotMax.setMaximum(999999999.0)
        self.yPlotMax.setProperty("value", 140.0)
        self.yPlotMax.setObjectName("yPlotMax")
        self.gridLayout_3.addWidget(self.yPlotMax, 3, 2, 1, 1)
        self.xPlotMin = QtWidgets.QDoubleSpinBox(ranges)
        self.xPlotMin.setMinimumSize(QtCore.QSize(0, 20))
        self.xPlotMin.setMinimum(-999999999.0)
        self.xPlotMin.setMaximum(999999999.0)
        self.xPlotMin.setProperty("value", 10.0)
        self.xPlotMin.setObjectName("xPlotMin")
        self.gridLayout_3.addWidget(self.xPlotMin, 2, 1, 1, 1)
        self.xPlotFullscale = QtWidgets.QPushButton(ranges)
        self.xPlotFullscale.setMinimumSize(QtCore.QSize(0, 20))
        self.xPlotFullscale.setObjectName("xPlotFullscale")
        self.gridLayout_3.addWidget(self.xPlotFullscale, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(ranges)
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.wavePlotMin = QtWidgets.QDoubleSpinBox(ranges)
        self.wavePlotMin.setMinimumSize(QtCore.QSize(0, 20))
        self.wavePlotMin.setMaximum(999999999.0)
        self.wavePlotMin.setProperty("value", 500.0)
        self.wavePlotMin.setObjectName("wavePlotMin")
        self.gridLayout_3.addWidget(self.wavePlotMin, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(ranges)
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(ranges)
        self.label_13.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 1, 1)
        self.colorPlotMin = QtWidgets.QDoubleSpinBox(ranges)
        self.colorPlotMin.setMinimumSize(QtCore.QSize(0, 20))
        self.colorPlotMin.setMinimum(1.0)
        self.colorPlotMin.setMaximum(1000000000.0)
        self.colorPlotMin.setSingleStep(100.0)
        self.colorPlotMin.setObjectName("colorPlotMin")
        self.gridLayout_3.addWidget(self.colorPlotMin, 6, 1, 1, 1)
        self.colorPlotMax = QtWidgets.QDoubleSpinBox(ranges)
        self.colorPlotMax.setMinimumSize(QtCore.QSize(0, 20))
        self.colorPlotMax.setMinimum(1.0)
        self.colorPlotMax.setMaximum(1000000000.0)
        self.colorPlotMax.setSingleStep(100.0)
        self.colorPlotMax.setProperty("value", 1000.0)
        self.colorPlotMax.setObjectName("colorPlotMax")
        self.gridLayout_3.addWidget(self.colorPlotMax, 6, 2, 1, 1)
        self.wavePlotFullscale = QtWidgets.QPushButton(ranges)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wavePlotFullscale.sizePolicy().hasHeightForWidth())
        self.wavePlotFullscale.setSizePolicy(sizePolicy)
        self.wavePlotFullscale.setObjectName("wavePlotFullscale")
        self.gridLayout_3.addWidget(self.wavePlotFullscale, 4, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.colorMap = QtWidgets.QComboBox(ranges)
        self.colorMap.setMinimumSize(QtCore.QSize(0, 23))
        self.colorMap.setObjectName("colorMap")
        self.gridLayout_2.addWidget(self.colorMap, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(ranges)
        self.label_14.setMinimumSize(QtCore.QSize(60, 0))
        self.label_14.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.plotMode = QtWidgets.QComboBox(ranges)
        self.plotMode.setMinimumSize(QtCore.QSize(120, 23))
        self.plotMode.setMaxVisibleItems(2)
        self.plotMode.setObjectName("plotMode")
        self.plotMode.addItem("")
        self.plotMode.addItem("")
        self.horizontalLayout_4.addWidget(self.plotMode)
        self.scaleMode = QtWidgets.QComboBox(ranges)
        self.scaleMode.setMinimumSize(QtCore.QSize(60, 23))
        self.scaleMode.setObjectName("scaleMode")
        self.scaleMode.addItem("")
        self.scaleMode.addItem("")
        self.horizontalLayout_4.addWidget(self.scaleMode)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(ranges)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 0, 1, 1)
        self.colorMapReversed = QtWidgets.QCheckBox(ranges)
        self.colorMapReversed.setObjectName("colorMapReversed")
        self.gridLayout_2.addWidget(self.colorMapReversed, 1, 2, 1, 1)
        self.keepAspRatio = QtWidgets.QCheckBox(ranges)
        self.keepAspRatio.setObjectName("keepAspRatio")
        self.gridLayout_2.addWidget(self.keepAspRatio, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label_17 = QtWidgets.QLabel(ranges)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spPlotAutoscaleCheckbox = QtWidgets.QCheckBox(ranges)
        self.spPlotAutoscaleCheckbox.setMinimumSize(QtCore.QSize(100, 0))
        self.spPlotAutoscaleCheckbox.setObjectName("spPlotAutoscaleCheckbox")
        self.horizontalLayout_6.addWidget(self.spPlotAutoscaleCheckbox)
        self.saveSpectrum = QtWidgets.QPushButton(ranges)
        self.saveSpectrum.setObjectName("saveSpectrum")
        self.horizontalLayout_6.addWidget(self.saveSpectrum)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.plotUpdate = QtWidgets.QPushButton(ranges)
        self.plotUpdate.setMinimumSize(QtCore.QSize(100, 40))
        self.plotUpdate.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plotUpdate.setFont(font)
        self.plotUpdate.setObjectName("plotUpdate")
        self.horizontalLayout_6.addWidget(self.plotUpdate)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        
        # --- Angular Linecut Controls ---
        linecut_group = QGroupBox("Angular Linecut")
        linecut_form_layout = QFormLayout(linecut_group)
        linecut_form_layout.setLabelAlignment(Qt.AlignRight)
        linecut_form_layout.setHorizontalSpacing(14)
        linecut_form_layout.setVerticalSpacing(6)
        linecut_form_layout.setFieldGrowthPolicy(QFormLayout.ExpandingFieldsGrow)

        self.linecut_center_x = QDoubleSpinBox(); self.linecut_center_x.setRange(-100.0, 100.0); self.linecut_center_x.setDecimals(3)
        self.linecut_center_y = QDoubleSpinBox(); self.linecut_center_y.setRange(-100.0, 100.0); self.linecut_center_y.setDecimals(3)
        self.linecut_angle = QDoubleSpinBox(); self.linecut_angle.setRange(0, 360); self.linecut_angle.setWrapping(True)
        self.linecut_points = QSpinBox(); self.linecut_points.setRange(2, 1000); self.linecut_points.setValue(100)
        linecut_form_layout.addRow("Number of Points:", self.linecut_points)

        # (NEW) Figure size controls
        self.linecut_fig_w = QDoubleSpinBox(); self.linecut_fig_w.setRange(2.0, 30.0); self.linecut_fig_w.setValue(7.0); self.linecut_fig_w.setDecimals(2)
        self.linecut_fig_h = QDoubleSpinBox(); self.linecut_fig_h.setRange(2.0, 30.0); self.linecut_fig_h.setValue(6.0); self.linecut_fig_h.setDecimals(2)
        linecut_form_layout.addRow("Fig Width (in):", self.linecut_fig_w)
        linecut_form_layout.addRow("Fig Height (in):", self.linecut_fig_h)

        self.linecut_mode = QComboBox()
        self.linecut_mode.addItems(["Stacked", "Map"])
        linecut_form_layout.addRow("Display:", self.linecut_mode)

        self.plot_angular_linecut_button = QPushButton("Plot Angular Linecut")
        linecut_form_layout.addRow(self.plot_angular_linecut_button)

        self.verticalLayout.addWidget(linecut_group)
        # --- End Angular Linecut ---

        #Mauro's change:
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_bck_title = QtWidgets.QLabel(ranges)
        self.label_bck_title.setFont(font)
        self.label_bck_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_bck_title.setObjectName("label_bck_title")
        self.horizontalLayout_7.addWidget(self.label_bck_title)
        
        self.isDifRef = QtWidgets.QCheckBox(ranges)
        self.isDifRef.setEnabled(True)
        self.isDifRef.setMaximumSize(QtCore.QSize(100, 16777215))
        self.isDifRef.setChecked(False)
        self.isDifRef.setObjectName("isDifRef")
        self.horizontalLayout_7.addWidget(self.isDifRef)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        
        self.label_bckRangeX = QtWidgets.QLabel(ranges)
        self.label_bckRangeX.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_bckRangeX.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bckRangeX.setObjectName("label_bckRangeY")
        self.gridLayout_4.addWidget(self.label_bckRangeX, 0, 1, 1, 1)
        
        self.label_bckRangeY = QtWidgets.QLabel(ranges)
        self.label_bckRangeY.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_bckRangeY.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bckRangeY.setObjectName("label_bckRangeY")
        self.gridLayout_4.addWidget(self.label_bckRangeY, 0, 2, 1, 1)
        
        self.label_bckRange = QtWidgets.QLabel(ranges)
        self.label_bckRange.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_bckRange.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bckRange.setObjectName("label_bckRange")
        self.gridLayout_4.addWidget(self.label_bckRange, 1, 0, 1, 1)
        
        self.yBck = QtWidgets.QDoubleSpinBox(ranges)
        self.yBck.setMinimumSize(QtCore.QSize(0, 20))
        self.yBck.setMinimum(0.0)
        self.yBck.setMaximum(150.0)
        self.yBck.setSingleStep(0.1)
        self.yBck.setProperty("value", 0.0)
        self.yBck.setObjectName("yBck")
        self.gridLayout_4.addWidget(self.yBck, 1, 2, 1, 1)
        
        self.xBck = QtWidgets.QDoubleSpinBox(ranges)
        self.xBck.setMinimumSize(QtCore.QSize(0, 20))
        self.xBck.setMinimum(0.0)
        self.xBck.setMaximum(150.0)
        self.xBck.setSingleStep(0.1)
        self.xBck.setProperty("value", 0.0)
        self.xBck.setObjectName("xBck")
        self.gridLayout_4.addWidget(self.xBck, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        
      
        
        

        self.retranslateUi(ranges)
        self.plotMode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ranges)
        ranges.setTabOrder(self.filePath, self.selectFileButton)
        ranges.setTabOrder(self.selectFileButton, self.xMeasMin)
        ranges.setTabOrder(self.xMeasMin, self.xMeasStep)
        ranges.setTabOrder(self.xMeasStep, self.xMeasMax)
        ranges.setTabOrder(self.xMeasMax, self.squareMeas)
        ranges.setTabOrder(self.squareMeas, self.yMeasMin)
        ranges.setTabOrder(self.yMeasMin, self.yMeasStep)
        ranges.setTabOrder(self.yMeasStep, self.yMeasMax)
        ranges.setTabOrder(self.yMeasMax, self.xPlotMin)
        ranges.setTabOrder(self.xPlotMin, self.xPlotMax)
        ranges.setTabOrder(self.xPlotMax, self.xPlotFullscale)
        ranges.setTabOrder(self.xPlotFullscale, self.yPlotMin)
        ranges.setTabOrder(self.yPlotMin, self.yPlotMax)
        ranges.setTabOrder(self.yPlotMax, self.yPlotFullscale)
        ranges.setTabOrder(self.yPlotFullscale, self.wavePlotMin)
        ranges.setTabOrder(self.wavePlotMin, self.wavePlotMax)
        ranges.setTabOrder(self.wavePlotMax, self.colorPlotMin)
        ranges.setTabOrder(self.colorPlotMin, self.colorPlotMax)
        ranges.setTabOrder(self.colorPlotMax, self.plotMode)
        ranges.setTabOrder(self.plotMode, self.scaleMode)
        ranges.setTabOrder(self.scaleMode, self.colorMap)
        ranges.setTabOrder(self.colorMap, self.isDifRef)
        ranges.setTabOrder(self.isDifRef, self.xBck)
        ranges.setTabOrder(self.xBck, self.yBck)

    def retranslateUi(self, ranges):
        _translate = QtCore.QCoreApplication.translate
        ranges.setWindowTitle(_translate("ranges", "Define ranges"))
        self.label_15.setText(_translate("ranges", "File path:"))
        self.selectFileButton.setText(_translate("ranges", "Select"))
        self.label_9.setText(_translate("ranges", "Measurement properties"))
        self.isSpaceMap.setToolTip(_translate("ranges", "<html><head/><body><p>Plot a space map. If unchecked, will plot <br/>a stack of spectra with index vs wavelength.</p></body></html>"))
        self.isSpaceMap.setText(_translate("ranges", "space map"))
        self.squareMeas.setText(_translate("ranges", "square"))
        self.label_5.setText(_translate("ranges", "Y"))
        self.label_2.setText(_translate("ranges", "minimum (V)"))
        self.label_3.setText(_translate("ranges", "step (V)"))
        self.label_4.setText(_translate("ranges", "maximum (V)"))
        self.label.setText(_translate("ranges", "X"))
        self.label_10.setText(_translate("ranges", "Color plot properties"))
        self.yPlotFullscale.setText(_translate("ranges", "Fullscale"))
        self.label_11.setText(_translate("ranges", "X"))
        self.label_12.setText(_translate("ranges", "Y"))
        self.label_6.setText(_translate("ranges", "Color range"))
        self.colorPlotFullscale.setText(_translate("ranges", "Full"))
        self.colorPlotAutoscale.setToolTip(_translate("ranges", "<html><head/><body><p>Intelligent autoscale <br/>to avoid cosmic rays <br/>scaling issue.</p></body></html>"))
        self.colorPlotAutoscale.setText(_translate("ranges", "Auto"))
        self.xPlotFullscale.setText(_translate("ranges", "Fullscale"))
        self.label_8.setText(_translate("ranges", "max"))
        self.label_7.setText(_translate("ranges", "min"))
        self.label_13.setText(_translate("ranges", "Wavelength (nm)"))
        self.wavePlotFullscale.setText(_translate("ranges", "Fullscale"))
        self.label_14.setText(_translate("ranges", "Plot mode"))
        self.plotMode.setItemText(0, _translate("ranges", "Integrated intensity"))
        self.plotMode.setItemText(1, _translate("ranges", "Maximum intensity"))
        self.scaleMode.setToolTip(_translate("ranges", "Intensity color plot scale."))
        self.scaleMode.setItemText(0, _translate("ranges", "log"))
        self.scaleMode.setItemText(1, _translate("ranges", "lin"))
        self.label_16.setText(_translate("ranges", "Colormap"))
        self.colorMapReversed.setText(_translate("ranges", "Reversed"))
        self.keepAspRatio.setText(_translate("ranges", "Keep aspect ratio"))
        self.label_17.setText(_translate("ranges", "Spectrum plot properties"))
        self.spPlotAutoscaleCheckbox.setText(_translate("ranges", "Autoscale"))
        self.saveSpectrum.setText(_translate("ranges", "Save spectrum as text"))
        self.plotUpdate.setText(_translate("ranges", "Plot"))
        self.plotUpdate.setShortcut(_translate("ranges", "Return"))
        
        #Mauro's change:
        self.label_bck_title.setText(_translate("ranges", "Background spectrum"))
#        self.label_bck.setText(_translate("ranges", "X"))
        self.isDifRef.setToolTip(_translate("ranges", "<html><head/><body><p>Plot a differential reflectivity space map. If unchecked, will plot <br/>the original space map.</p></body></html>"))
        self.isDifRef.setText(_translate("ranges", "Diff. Refl."))
        self.label_bckRangeX.setText(_translate("ranges", "X"))
        self.label_bckRangeY.setText(_translate("ranges", "Y"))
        self.label_bckRange.setText(_translate("ranges", "Coordinates (V)"))

        # --- Angular Linecut ---
        self.plot_angular_linecut_button.setText(_translate("ranges", "Plot Angular Linecut"))

    # Mauro's change:
    def isDifRefClicked(self):
        self.ui.xBck.setValue(self.ui.xBck.value())
        self.ui.yBck.setValue(self.ui.yBck.value())

    # --- ADD THE ENTIRE NEW METHOD BELOW ---
    def plot_angular_linecut(self):
        """
        Calculates and plots spectra along a line defined by a center point and an angle.
        """
        if not self.f_fileOpen:
            errorMessageWindow(self, "No File", "Please open a data file first.")
            return

        # 1. Get parameters from UI
        center_x = self.ui.linecut_center_x.value()
        center_y = self.ui.linecut_center_y.value()
        angle_deg = self.ui.linecut_angle.value()
        num_points = self.ui.linecut_points.value()
        angle_rad = np.deg2rad(angle_deg)

        # 2. Define the line and sampling points
        # Calculate max distance to ensure the line crosses the whole map
        x_range = self.plotParams["xRange"]
        y_range = self.plotParams["yRange"]
        max_dist = np.sqrt((x_range[1] - x_range[0])**2 + (y_range[1] - y_range[0])**2)
        
        # Generate distances from the center point
        distances = np.linspace(-max_dist / 2, max_dist / 2, num_points)
        
        # Calculate coordinates of points along the line
        line_points_x = center_x + distances * np.cos(angle_rad)
        line_points_y = center_y + distances * np.sin(angle_rad)

        # 3. Find nearest spectra and collect them
        spectra_to_plot = []
        distances_to_plot = []
        unique_indices = set()

        for i in range(num_points):
            px, py = line_points_x[i], line_points_y[i]
            
            # Find the index of the spectrum nearest to the point (px, py)
            counts_idx, _ = self.determineWhichSpectrum(pos=(px, py), indexMove=(0, 0))

            if counts_idx not in unique_indices:
                unique_indices.add(counts_idx)
                # Store the spectrum and its distance from the center
                spectra_to_plot.append(self.counts[counts_idx])
                distances_to_plot.append(distances[i])

        if not spectra_to_plot:
            errorMessageWindow(self, "No Data", "No spectra found along the specified line.")
            return

        # 4. Visualize the collected spectra (Stacked Plot)
        fig, ax = pl.subplots(figsize=(10, 6))
        
        spectra_array = np.array(spectra_to_plot)
        offset_factor = 0.5  # Adjust this to change the spacing between plots
        offset = np.max(spectra_array) * offset_factor

        for i, spec in enumerate(spectra_array):
            ax.plot(self.wavelength, spec + i * offset)

        ax.set_title(f"Angular Linecut: Center=({center_x:.2f}, {center_y:.2f}), Angle={angle_deg}°")
        ax.set_xlabel("Wavelength (nm)")
        ax.set_ylabel("Intensity (counts, offset)")
        ax.get_yaxis().set_ticks([]) # Hide y-axis ticks as they are arbitrary
        fig.tight_layout()
        fig.show()

        # 5. Draw the line on the original map for visual feedback
        if self.f_mapOpen:
            # Remove previous linecut line if it exists
            for line in self.mainAxes.lines:
                if line.get_label() == '_linecut':
                    line.remove()
            
            self.mainAxes.plot(line_points_x, line_points_y, 'w--', linewidth=2, label='_linecut')
            self.fig.canvas.draw()


def plotVerticalBar(ax, xPos, *args, **kwargs):
    """Plot a vertical bar at xPos on the given axes."""
    ax.plot([xPos, xPos], ax.get_ylim(), *args, **kwargs)
