import csv
import pylatex
dict = {}
with open('Quantum Learning Submissions.csv',"r", encoding = "utf8") as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for val, row in enumerate(csv_reader):
        for val2, i in enumerate(row):
            dict[str(val)+','+str(val2)] = i

doc = pylatex.Document()
for j in range(1,val):
    if dict[str(j)+',8'] == 'q1':
        with doc.create(pylatex.Section(title = dict[str(j)+',7'], numbering = False)):
            doc.append(pylatex.basic.FootnoteText('Question:-  How can a quantum sensor optimally extract information about its environment?'))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.position.HorizontalSpace('15pt',star = False))
            doc.append(pylatex.utils.bold(dict[str(j)+',2'] + ' - '))
            doc.append(pylatex.utils.italic(dict[str(j)+',3']))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.utils.italic(dict[str(j)+',5']))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NoEscape(dict[str(j)+',9']))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.position.HorizontalSpace('15pt',star = False))
            doc.append(pylatex.utils.bold('Learning Techniques:- '))
            doc.append(dict[str(j)+',10'])
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append('Number : '+ dict[str(j)+',0'])
            doc.append(pylatex.position.HorizontalSpace('15pt',star = False))
            doc.append('Submitted : '+ dict[str(j)+',1'])
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append('Reference : '+ dict[str(j)+',11'])
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.utils.bold('Email:-'))
            doc.append(dict[str(j)+',4'])
            doc.append(pylatex.NewPage())
for j in range(1,val):
    if dict[str(j)+',8'] == 'q2':
        with doc.create(pylatex.Section(title = dict[str(j)+',7'], numbering = False)):
            doc.append(pylatex.basic.FootnoteText('Question:-  How can we achieve fully autonmatic calibration and operation of multi-qubit circuits?'))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.position.HorizontalSpace('15pt',star = False))
            doc.append(pylatex.utils.bold(dict[str(j)+',2'] + ' - '))
            doc.append(pylatex.utils.italic(dict[str(j)+',3']))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.utils.italic(dict[str(j)+',5']))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NoEscape(dict[str(j)+',9']))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.position.HorizontalSpace('15pt',star = False))
            doc.append(pylatex.utils.bold('Learning Techniques:- '))
            doc.append(dict[str(j)+',10'])
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append('Number : '+ dict[str(j)+',0'])
            doc.append(pylatex.position.HorizontalSpace('15pt',star = False))
            doc.append('Submitted : '+ dict[str(j)+',1'])
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append('Reference : '+ dict[str(j)+',11'])
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.utils.bold('Email:-'))
            doc.append(dict[str(j)+',4'])
            doc.append(pylatex.NewPage())
for j in range(1,val):
    if dict[str(j)+',8'] == 'q3':
        with doc.create(pylatex.Section(title = dict[str(j)+',7'], numbering = False)):
            doc.append(pylatex.basic.FootnoteText('Question:-  How can machine learning improve the performance of quantum algorithms for quantum chemistry'))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.position.HorizontalSpace('15pt',star = False))
            doc.append(pylatex.utils.bold(dict[str(j)+',2'] + ' - '))
            doc.append(pylatex.utils.italic(dict[str(j)+',3']))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.utils.italic(dict[str(j)+',5']))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NoEscape(dict[str(j)+',9']))
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.position.HorizontalSpace('15pt',star = False))
            doc.append(pylatex.utils.bold('Learning Techniques:- '))
            doc.append(dict[str(j)+',10'])
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append('Number : '+ dict[str(j)+',0'])
            doc.append(pylatex.position.HorizontalSpace('15pt',star = False))
            doc.append('Submitted : '+ dict[str(j)+',1'])
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append('Reference : '+ dict[str(j)+',11'])
            doc.append(pylatex.NewLine())
            doc.append(pylatex.NewLine())
            doc.append(pylatex.utils.bold('Email:-'))
            doc.append(dict[str(j)+',4'])
            doc.append(pylatex.NewPage())
doc.generate_pdf(filepath = 'QuantumLearningSubmissions',compiler = 'pdfLaTex')